### ISSUE TITLE
Write TT_Pad() and TT_Length

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/postTranslationEngine#25]
* Pad function to pad strings to specified number of characters.
* Padding should come before specified string.
* Arguments for string to be padded, number of total characters, pad value
* Error if provided string is longer than number of characters.

**Comment by pedrogit** [comment]
Translation function should never generate an error. A TT_Length() validation rule should be used to validate the length of the string prior to passing the value to TT_Pad(). TT_Pad() trunk the string if it's too long.
