### ISSUE TITLE
Implement beta version of translation engine

### ISSUE THREAD

**Issue by edwardsmarc** [edwardsmarc/postTranslationEngine#3]
* Should test 2-3 basic helper functions. 
* Should be able to validate input data. 
* Invalid rules could be simplified for beta (e.g. default to -9999). 
* Should run translation rules. 
* Config file parameters could be set to defaults for beta. 
* Logging and resuming not necessary for beta. 
* Should add photo year using shapefile if required.

**Comment by pedrogit** [comment]
Openned other issues for "Should be able to validate input data."
