### ISSUE TITLE
Add a boolean parameter to TT_Match and TT_Lookup to ignore case when comparing

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/postTranslationEngine#33]
The species lookup table fri_values are uppercase but the values in AB06 are mixed case. If we can add TRUE as a parameter to TT_Match and TT_Lookup so that they ignore case sensitiveness, that would solve the problem. The other option would be to create a mixed case lookup table but we can never garantee that source values will always follow the proper case.

**Comment by pedrogit** [comment]
I don't see this change in the source tree.

**Comment by edwardsmarc** [comment]
@pedrogit It should be there now. I had a merge conflict.
