### ISSUE TITLE
Implement TT_Match(), TT_Map(), and TT_Lookup helper functions

### ISSUE THREAD

**Issue by pedrogit** [edwardsmarc/postTranslationEngine#6]
Validation functions:
TT_Match(text,text[]) - is text in text[]?
TT_Match(text, name, name) - is text in first column of table name.name? 

Translation functions:
TT_Map(text[], text[]) - search for values in first array and return values in second array.
TT_Lookup(text,name,name,text) - search for values and in first column of table name.name and replace with values in specified column.

**Comment by edwardsmarc** [comment]
@pedrogit I've pushed my attempt at TT_MatchStr. Can you fix it? I get an error saying the column doesn't exist.

**Comment by pedrogit** [comment]
Was fixed. We might want to rename them to TT_Match() and TT_Lookup().

**Comment by edwardsmarc** [comment]
Done except for a list varient of TT_Map. This would return the value in a second list with an index matching the position of val in the first list. Is this needed? I've started writing it but can't figure out how to access an array within an EXECUTE.
